config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      put 'run', to: 'tasks#run'
      put 'complete', to: 'tasks#complete'
    end
  end

  devise_scope :user do
    post 'users/sign_up', to: 'users/registrations#create'
    put 'users/edit', to: 'users/registrations#update'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  root to: 'tasks#index'
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  include AASM

  default_scope { includes(:creator, :assigned_to).references(:creator, :assigned_to) }
  scope :tasks_for, ->(user) { where(assigned_to: user) }
  scope :tasks_from, ->(user) { where(creator: user) }

  belongs_to :creator, class_name: 'User'
  belongs_to :assigned_to, class_name: 'User'

  validates :title, presence: true
  validates :creator, presence: true
  validates :assigned_to, presence: true

  aasm column: :status do
    state :new, initial: true
    state :started
    state :finished

    event :run do
      transitions from: :new, to: :started
    end

    event :complete do
      transitions from: :started, to: :finished
    end
  end

  def can_be_edited?(user)
    creator == user
  end

  def can_be_destroyed?(user)
    creator == user
  end

  def can_be_ran?(user)
    new? && assigned_to == user
  end

  def can_be_completed?(user)
    started? && assigned_to == user
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy run complete]
  before_action :set_users_for_assings, only: %i[new edit update]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks_from_current_user = Task.tasks_from(current_user)
    @tasks_for_current_user = Task.tasks_for(current_user)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def run
    @task.run! if @task.new?
    redirect_to @task, notice: 'Task started!'
  end

  def complete
    @task.complete! if @task.started?
    redirect_to @task, notice: 'Task finished.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_users_for_assings
    @users_for_assigns = User.all - [current_user]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:title, :description, :creator_id, :assigned_to_id, :status)
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def action_show(task)
    link_to icon('fas', 'eye'), task, role: 'button',
                                      class: 'btn btn-sm btn-outline-info mr-1',
                                      title: 'Show'
  end

  def action_edit(task)
    link_to icon('fas', 'edit'), edit_task_path(task), role: 'button',
                                                       class: 'btn btn-sm btn-outline-warning mr-1',
                                                       title: 'Edit'
  end

  def action_destroy(task)
    link_to icon('fas', 'times'), task, data: { confirm: 'Are you sure?' },
                                        method: :delete,
                                        role: 'button',
                                        class: 'btn btn-sm btn-outline-danger mr-1',
                                        title: 'Destroy'
  end

  def action_run(task)
    link_to icon('fas', 'play', 'Start'), run_task_path(task), method: :put,
                                                               role: 'button',
                                                               class: 'btn btn-outline-success'
  end

  def action_complete(task)
    link_to icon('fas', 'flag-checkered', 'Finish'), complete_task_path(task), method: :put,
                                                                               role: 'button',
                                                                               class: 'btn btn-outline-primary'
  end
end

app/views/tasks/_form.html.slim
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :creator_id, value: current_user.id

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
    - if @task.errors.messages[:title].any?
      .invalid-feedback
        = error_message_for(@task, :title)

  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control'

  .form-group
    = f.label :assigned_to_id
    = f.collection_select :assigned_to_id, @users_for_assigns, :id, :full_name, {}, class: 'form-control'

  .form-group
    = f.label :status
    = f.text_field :status, class: 'form-control', disabled: true

  .actions = f.submit class: 'btn btn-primary' 

app/views/tasks/edit.html.slim
h1.mt-4 Editing task

.mt-3.mb-3
  = link_to icon('fas', 'arrow-circle-left', 'Back'), tasks_path, role: 'button', class: 'btn btn-secondary mr-1'
  = link_to icon('fas', 'eye', 'Show'), @task, role: 'button', class: 'btn btn-warning'

.row
  .col-lg-6
    == render 'form'

app/views/tasks/index.html.slim
h1.mt-4 Tasks
.mt-3.mb-3
  = link_to 'New Task', new_task_path, role: 'button', class: 'btn btn-primary'

.row
  .col
    .card
      .card-header
        nav
          #nav-tab.nav.nav-tabs.card-header-tabs role="tablist"
            a#nav-assignedToMe-tab.nav-item.nav-link.active [data-toggle="tab" href="#nav-assignedToMe" role="tab"
              aria-controls="nav-assignedToMe" aria-selected="true"]
              | Assigned to me
              span.badge.badge-success.ml-1 = @tasks_for_current_user.count
            a#nav-created-by-me-tab.nav-item.nav-link [data-toggle="tab" href="#nav-createdByMe" role="tab"
              aria-controls="nav-createdByMe" aria-selected="false"]
              | Created by me
              span.badge.badge-success.ml-1 = @tasks_from_current_user.count

      .card-body
        #nav-tasksTabContent.tab-content
          #nav-assignedToMe.tab-pane.fade.show.active role="tabpanel" aria-labelledby="nav-assignedToMe-tab"
            - if @tasks_for_current_user.blank?
              p.mt-3.pl-3 No tasks
            - else
              = render template: 'tasks/partials/_table', locals: { tasks: @tasks_for_current_user, user_type: :creator }

          #nav-createdByMe.tab-pane.fade role="tabpanel" aria-labelledby="nav-createdByMe-tab"
            - if @tasks_from_current_user.blank?
              p.mt-3.pl-3 No tasks
            - else
              = render template: 'tasks/partials/_table', locals: { tasks: @tasks_from_current_user, user_type: :assigned_to }

app/views/tasks/new.html.slim
h1.mt-4 New task

.mt-3.mb-3
  = link_to icon('fas', 'arrow-circle-left', 'Back'), tasks_path, role: 'button', class: 'btn btn-secondary'

.row
  .col-lg-6
    == render 'form'

app/views/tasks/show.html.slim
h1.mt-4 = @task.title

.mt-3.mb-3
  = link_to icon('fas', 'arrow-circle-left', 'Back'), tasks_path, role: 'button', class: 'btn btn-secondary mr-1'
  - if @task.can_be_edited? current_user
    = link_to icon('fas', 'eye', 'Edit'), edit_task_path(@task), role: 'button', class: 'btn btn-warning mr-1'
  - if @task.can_be_ran? current_user
    = action_run(@task)
  - elsif @task.can_be_completed? current_user
    = action_complete(@task)

.row.pl-3.mt-1
  .col-lg-6
    .row
      p.col-lg-4.border.text-center Title
      p.col-lg-8 = @task.title
    .row
      p.col-lg-4.border.text-center Description
      p.col-lg-8 = @task.description
    .row
      p.col-lg-4.border.text-center Creator
      p.col-lg-8 = @task.creator.full_name
    .row
      p.col-lg-4.border.text-center Assigned to
      p.col-lg-8 = @task.assigned_to.full_name
    .row
      p.col-lg-4.border.text-center Status
      p.col-lg-8 = @task.status.humanize